export const REQUEST_TODOS = "todos/REQUEST_TODOS";
export type REQUEST_TODOS = typeof REQUEST_TODOS;

export const REQUEST_TODOS_SUCCESS = "todos/REQUEST_TODOS_SUCCESS";
export type REQUEST_TODOS_SUCCESS = typeof REQUEST_TODOS_SUCCESS;

export const REQUEST_TODOS_ERROR = "todos/REQUEST_TODOS_ERROR";
export type REQUEST_TODOS_ERROR = typeof REQUEST_TODOS_ERROR;
